#
# Unified deployment workflow - handles both initial deploy and updates
#
name: Deploy to Production

on:
    push:
        branches: [prod]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Deploy or Update Application
              uses: appleboy/ssh-action@v0.1.9
              with:
                  host: ${{ secrets.LINODE_HOST }}
                  key: ${{ secrets.LINODE_SSH_KEY }}
                  username: ${{ secrets.LINODE_USER }}
                  script: |
                      cd ${{ secrets.DEPLOY_PATH }}
                      
                      # Check if project directory exists
                      if [ -d "${{ secrets.PROJECT_PATH }}" ]; then
                          echo "📦 Existing deployment found - performing update..."
                          cd ${{ secrets.PROJECT_PATH }}
                          
                          # Update existing deployment
                          git fetch --all
                          git reset --hard origin/${{ secrets.BRANCH_NAME }}
                          npm ci --production
                          
                          # Check if .env file exists
                          if [ -f ".env" ]; then
                              # Restart PM2 process
                              pm2 restart "${{ secrets.PM2_PROCESS_NAME }}" || pm2 start index.js --name "${{ secrets.PM2_PROCESS_NAME }}"
                              echo "✅ Update completed successfully"
                          else
                              echo "⚠️ .env file is missing. Skipping PM2 start/restart."
                          fi
                      else
                          echo "🚀 No existing deployment found - performing initial deployment..."
                          
                          # Create project directory
                          mkdir -p ${{ secrets.PROJECT_PATH }}
                          cd ${{ secrets.PROJECT_PATH }}
                          
                          # Clone repository
                          git clone ${{ secrets.REPO_URL }} .
                          git checkout ${{ secrets.BRANCH_NAME }}
                          
                          # Install dependencies
                          npm ci --production
                          
                          # Check if .env file exists
                          if [ -f ".env" ]; then
                              # Start PM2 process
                              pm2 start index.js --name "${{ secrets.PM2_PROCESS_NAME }}"
                              pm2 save
                              echo "✅ Initial deployment completed successfully"
                          else
                              echo "⚠️ .env file is missing. Skipping PM2 start."
                          fi
                      fi

                      # Show PM2 status
                      pm2 status ${{ secrets.PM2_PROCESS_NAME }}
